theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge
url: https://matthewritch.com
permalink: pretty
title: Matthew Ritch
description: >-
  Personal website of Matthew Ritch — engineering and product professional.
author: Matthew Ritch
plugins:
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - blogideas.txt
  - notes.txt
  - README.md
  - context
  